site_name:  IMXNOOBX
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon64.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: green
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - content.code.annotate 
    - content.tabs.link
extra:
  homepage: https://docs.imxnoobx.xyz
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/imxnoobx
      name: IMXNOOBX on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/IMXNOOBX
      name: IMXNOOBX on GitHub
copyright: Copyright &copy; 2021 - 2022 IMXNOOBX
repo_url: https://github.com/IMXNOOBX/imxnoobx.xyz
repo_name: imxnoobx.xyz
nav:
  - Welcome: 
      - Welcome: 'index.md'
      - Contribute: 'contribute.md'
      - Credits: 'credits.md'
  - 'Rest API':
      - 'Restfull API': 'rest-api\index.md'
      - 'Discord Users': 'rest-api\discord-user.md'
      - 'Discord Servers': 'rest-api\discord-server.md'
      - 'Steam Users': 'rest-api\steam-user.md'
      - 'Scam Link Analyzer': 'rest-api\scamlink-detector.md'
      - 'Error Handling': 'rest-api\handle-errors.md'
  - 'Discord Logger':
      - 'Discord Logger': 'dis-logs\index.md'
      - Information: 'dis-logs\information.md'
      - Instalation: 'dis-logs\instalation.md'
      - Usage: 'dis-logs\usage.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html